#!/bin/bash
#SBATCH -J BnC1
#SBATCH --partition weekend
#SBATCH --time=36:00:00
#SBATCH --nodes=25
#SBATCH --ntasks-per-node=24
#SBATCH --output=test.output
#SBATCH --dependency=afterany:644160
#SBATCH --mail-user=agarwal@cerfacs.fr

python chain.py > chain_${SLURM_JOB_ID}.out

module purge
module load avbp/7.X

cd $SLURM_SUBMIT_DIR

mpirun -np $SLURM_NTASKS /data/home/cfd/agarwal/AVBP_dev/HOST/NEMO/BIN/AVBP_V7_dev.NEMO > output
